### ISSUE TITLE
How to make it heroku Deploy

### ISSUE THREAD

**Issue by WSrujan** [DivyaKumarBaid/Youtube_promotion_on_twitter#3]

**Comment by DivyaKumarBaid** [comment]
To host on Heroku you need to have at least a private repo in your Github, then head over to Heroku sign in and then click on new and create a new app. Provide the app name, choose the region and then click create, you need to connect your Github profile there, and then under the deployment section choose GitHub and then choose your repo.

if there is still a doubt I am posting a YT link here so you can go through that.....
https://youtu.be/aUW5GAFhu6s


remember this is not my video.....

Happy Deployment!
